import { ReactNode } from "react";
import StoreProvider from "../AppProvider";
import "./globals.css";

export const metadata = {
  title: "skribbl",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
